spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: eureka-consumer-feign

          uri: lb://EUREKA-CONSUMER-FEIGN #最终转发地址
          order: 0
          predicates:
            - Path=/eureka-consumer-feign/**  # 断言，路径相匹配的进行路由*/
          filters:
            - StripPrefix=1 #转发的时候在微服务中要去掉前一层网关的地址
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar

server:
  port: 10000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
