spring:
  application:
    name: cloud-gateway
  redis:
    host: localhost
    port: 6379
    database: 0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      default-filters:
        - Elapsed=true
      routes:
        - id: eureka-consumer-feign
          uri: lb://EUREKA-CONSUMER-FEIGN #最终转发地址
          order: 0
          predicates:
            - Path=/eureka-consumer-feign/**  # 断言，路径相匹配的进行路由*/
          filters:
            - StripPrefix=1 #转发的时候在微服务中要去掉前一层网关的地址
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 1 #令牌桶每秒填充平均速率。
                redis-rate-limiter.burstCapacity: 5 #令牌桶容量。
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar

server:
  port: 10000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
    #logging:
    #level:
    # org.springframework.cloud.gateway: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"



        #熔断相关配置
        #hystrix:
        #command:
        #default:
        #circuitBreaker:
        # 强制将断路器设置成开启状态
        #forceOpen: true