spring:
  application:
    name: eureka-consumer-feign
eureka:
  client:
    service-url:
      defaultZone: http://192.168.32.20:7000/eureka/,http://192.168.32.20:7001/eureka/,192.168.32.20://peer2:7002/eureka/
server:
  port: 9001
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
